SUPABASE_URL="https://wmbfkirxhivnavwaapkq.supabase.co"


SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYmZraXJ4aGl2bmF2d2FhcGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwNjUzNjUsImV4cCI6MjA5NjY0MTM2NX0.edGjHsq-6L0aGqubB6HsdcxOl5gxPmUgJXXucBvAFtY"